name: Update README

on:
  push:
    branches:
      - readme_update

jobs:
  update-readme:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update README
      run: |
        DATE=`date +%d-%m-%Y`
        sed -i "s/{_DATE_}/$DATE/" README.md
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Last update README, updated"
        git push
